apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
reclaimPolicy: Retain  
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer #storage class is created when pod is getting created 
parameters: 
  provisioningMode: efs-ap
  fileSystemId: # our custom files system id
  basePath: "/expense"
